name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0-91.0.dev <4.0.0"
dependencies:
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
dev_dependencies:
  # arb_gen: ^0.0.3
  arb_gen:
    path: ..
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true




