///
/// languageMap
/// Impressive! This language map is thorough and covers a diverse
/// range of languages. It's great for handling localization in your
/// application. If you have any questions or need assistance with
/// anything related to this code or beyond, feel free to ask!
// const Map<String, Map<String, String>> LANGS = {
//   // 'af': {'Afrikaans': 'Afrikaans'},
//   'sq': {'Albanian': 'Shqiptar'},
//   // 'am': {'Amharic': 'አማርኛ'},
//   'ar': {'Arabic': 'العربية'},
//   'hy': {'Armenian': 'Հայերեն'},
//   'az': {'Azerbaijani': 'Azərbaycan dili'},
//   'eu': {'Basque': 'Euskara'},
//   'be': {'Belarusian': 'Беларуская мова'},
//   'bn': {'Bengali': 'বাংলা'},
//   'bs': {'Bosnian': 'Bosanski'},
//   'bg': {'Bulgarian': 'Български'},
//   // 'ca': {'Catalan': 'Català'},
//   // 'zh-Hans': {'Chinese (Simplified)': '中文(简体)'},
//   'zh-Hant': {'Chinese (Traditional)': '中文(繁體)'},
//   'hr': {'Croatian': 'Hrvatski'},
//   'cs': {'Czech': 'Čeština'},
//   'da': {'Danish': 'Dansk'},
//   'nl': {'Dutch': 'Nederlands'},
//   'en': {'English': 'English'},
//   'et': {'Estonian': 'Eesti'},
//   'tl': {'Filipino': 'Filipino'},
//   'fi': {'Finnish': 'Suomi'},
//   'fr': {'French': 'Français'},
//   'gl': {'Galician': 'Galego'},
//   'ka': {'Georgian': 'ქართული'},
//   'de': {'German': 'Deutsch'},
//   'el': {'Greek': 'Ελληνικά'},
//   'gu': {'Gujarati': 'ગુજરાતી'},
//   'ht': {'Haitian Creole': 'Kreyòl Ayisyen'},
//   'ha': {'Hausa': 'Hausa'},
//   'haw': {'Hawaiian': 'ʻŌlelo Hawaiʻi'},
//   'iw': {'Hebrew': 'עברית'},
//   'hi': {'Hindi': 'हिन्दी'},
//   'hmn': {'Hmong': 'Hmong'},
//   'hu': {'Hungarian': 'Magyar'},
//   'is': {'Icelandic': 'Íslenska'},
//   'ig': {'Igbo': 'Igbo'},
//   'id': {'Indonesian': 'Bahasa Indonesia'},
//   'ga': {'Irish': 'Gaeilge'},
//   'it': {'Italian': 'Italiano'},
//   'ja': {'Japanese': '日本語'},
//   // 'jw': {'Javanese': 'Basa Jawa'},
//   'kn': {'Kannada': 'ಕನ್ನಡ'},
//   'kk': {'Kazakh': 'Қазақ тілі'},
//   'km': {'Khmer': 'ភាសាខ្មែរ'},
//   'rw': {'Kinyarwanda': 'Kinyarwanda'},
//   'ko': {'Korean': '한국어'},
//   'ku': {'Kurdish (Kurmanji)': 'Kurdî (Kurmancî)'},
//   'ky': {'Kyrgyz': 'Кыргызча'},
//   'lo': {'Lao': 'ພາສາລາວ'},
//   'la': {'Latin': 'Latine'},
//   'lv': {'Latvian': 'Latviešu valoda'},
//   'lt': {'Lithuanian': 'Lietuvių kalba'},
//   'lb': {'Luxembourgish': 'Lëtzebuergesch'},
//   'mk': {'Macedonian': 'Македонски'},
//   'mg': {'Malagasy': 'Malagasy'},
//   'ms': {'Malay': 'Bahasa Melayu'},
//   'ml': {'Malayalam': 'മലയാളം'},
//   'mt': {'Maltese': 'Malti'},
//   'mi': {'Maori': 'Te Reo Māori'},
//   'mr': {'Marathi': 'मराठी'},
//   'mn': {'Mongolian': 'Монгол'},
//   'my': {'Burmese': 'မြန်မာစာ'},
//   'ne': {'Nepali': 'नेपाली'},
//   'no': {'Norwegian': 'Norsk'},
//   'ps': {'Pashto': 'پښتو'},
//   'fa': {'Persian': 'فارسی'},
//   'pl': {'Polish': 'Polski'},
//   'pt': {'Portuguese': 'Português'},
//   'pa': {'Punjabi': 'ਪੰਜਾਬੀ'},
//   'ro': {'Romanian': 'Română'},
//   'ru': {'Russian': 'Русский'},
//   'sm': {'Samoan': 'Gagana Samoa'},
//   'gd': {'Scots Gaelic': 'Gàidhlig na h-Alba'},
//   'sr': {'Serbian': 'Српски'},
//   'st': {'Sesotho': 'Sesotho'},
//   'sn': {'Shona': 'ChiShona'},
//   'sd': {'Sindhi': 'سنڌي'},
//   'si': {'Sinhala': 'සිංහල'},
//   'sk': {'Slovak': 'Slovenčina'},
//   'sl': {'Slovenian': 'Slovenščina'},
//   'so': {'Somali': 'Soomaali'},
//   'es': {'Spanish': 'Español'},
//   'su': {'Sundanese': 'Basa Sunda'},
//   'sw': {'Swahili': 'Kiswahili'},
//   'sv': {'Swedish': 'Svenska'},
//   'tg': {'Tajik': 'Тоҷикӣ'},
//   'ta': {'Tamil': 'தமிழ்'},
//   'te': {'Telugu': 'తెలుగు'},
//   'th': {'Thai': 'ไทย'},
//   'tr': {'Turkish': 'Türkçe'},
//   'uk': {'Ukrainian': 'Українська'},
//   'ur': {'Urdu': 'اردو'},
//   'ug': {'Uyghur': 'Uyƣurqə'},
//   'uz': {'Uzbek': 'Oʻzbekcha'},
//   'vi': {'Vietnamese': 'Tiếng Việt'},
//   'cy': {'Welsh': 'Cymraeg'},
//   'xh': {'Xhosa': 'isiXhosa'},
//   'yi': {'Yiddish': 'ייִדיש'},
//   'yo': {'Yoruba': 'Yorùbá'},
//   'zu': {'Zulu': 'isiZulu'},
//   'he': {'עברית': 'Hebrew'},
//   'tt': {'Татар': 'Tatar'},
//   'tk': {'Türkmen': 'Turkmen'},
// };

/// Impressive! This language map is thorough and covers a diverse
/// range of languages. It's great for handling localization in your
/// application. If you have any questions or need assistance with
/// anything related to this code or beyond, feel free to ask!
library;
const Map<String, Map<String, String>> FlutterSupportedLanguages = {
  'af': {'Afrikaans': 'Afrikaans'},
  'am': {'Amharic': 'አማርኛ'},
  'ar': {'Arabic': 'العربية'},
  'as': {'Assamese': 'অসমীয়া'},
  'az': {'Azerbaijani': 'Azərbaycan dili'},
  'be': {'Belarusian': 'Беларуская мова'},
  'bg': {'Bulgarian': 'Български'},
  'bn': {'Bengali Bangla': 'বাংলা'},
  'bs': {'Bosnian': 'Bosanski'},
  'ca': {'Catalan Valencian': 'Català'},
  'cs': {'Czech': 'Čeština'},
  'cy': {'Welsh': 'Cymraeg'},
  'da': {'Danish': 'Dansk'},
  'de': {'German': 'Deutsch'},
  'el': {'Modern Greek': 'Ελληνικά'},
  'en': {'English': 'English'},
  'es': {'Spanish Castilian': 'Español'},
  'et': {'Estonian': 'Eesti'},
  'eu': {'Basque': 'Euskara'},
  'fa': {'Persian': 'فارسی'},
  'fi': {'Finnish': 'Suomi'},
  'fil': {'Filipino Pilipino': 'Filipino'},
  'fr': {'French': 'Français'},
  'gl': {'Galician': 'Galego'},
  'gsw': {'Swiss German Alemannic Alsatian': 'Schwyzertüütsch'},
  'gu': {'Gujarati': 'ગુજરાતી'},
  'he': {'Hebrew': 'עברית'},
  'hi': {'Hindi': 'हिन्दी'},
  'hr': {'Croatian': 'Hrvatski'},
  'hu': {'Hungarian': 'Magyar'},
  'hy': {'Armenian': 'Հայերեն'},
  'id': {'Indonesian': 'Bahasa Indonesia'},
  'is': {'Icelandic': 'Íslenska'},
  'it': {'Italian': 'Italiano'},
  'ja': {'Japanese': '日本語'},
  'ka': {'Georgian': 'ქართული'},
  'kk': {'Kazakh': 'Қазақ тілі'},
  'km': {'Khmer Central Khmer': 'ភាសាខ្មែរ'},
  'kn': {'Kannada': 'ಕನ್ನಡ'},
  'ko': {'Korean': '한국어'},
  'ky': {'Kirghiz Kyrgyz': 'Кыргызча'},
  'lo': {'Lao': 'ພາສາລາວ'},
  'lt': {'Lithuanian': 'Lietuvių kalba'},
  'lv': {'Latvian': 'Latviešu valoda'},
  'mk': {'Macedonian': 'Македонски'},
  'ml': {'Malayalam': 'മലയാളം'},
  'mn': {'Mongolian': 'Монгол'},
  'mr': {'Marathi': 'मराठी'},
  'ms': {'Malay': 'Bahasa Melayu'},
  'my': {'Burmese': 'မြန်မာစာ'},
  'nb': {'Norwegian Bokmål': 'Norsk bokmål'},
  'ne': {'Nepali': 'नेपाली'},
  'nl': {'Dutch Flemish': 'Nederlands'},
  'no': {'Norwegian': 'Norsk'},
  'or': {'Oriya': 'ଓଡ଼ିଆ'},
  'pa': {'Panjabi Punjabi': 'ਪੰਜਾਬੀ'},
  'pl': {'Polish': 'Polski'},
  'ps': {'Pushto Pashto': 'پښتو'},
  'pt': {'Portuguese': 'Português'},
  'ro': {'Romanian Moldavian Moldovan': 'Română'},
  'ru': {'Russian': 'Русский'},
  'si': {'Sinhala Sinhalese': 'සිංහල'},
  'sk': {'Slovak': 'Slovenčina'},
  'sl': {'Slovenian': 'Slovenščina'},
  'sq': {'Albanian': 'Shqiptar'},
  'sr': {'Serbian': 'Српски'},
  'sv': {'Swedish': 'Svenska'},
  'sw': {'Swahili': 'Kiswahili'},
  'ta': {'Tamil': 'தமிழ்'},
  'te': {'Telugu': 'తెలుగు'},
  'th': {'Thai': 'ไทย'},
  'tl': {'Tagalog': 'Tagalog'},
  'tr': {'Turkish': 'Türkçe'},
  'uk': {'Ukrainian': 'Українська'},
  'ur': {'Urdu': 'اردو'},
  'uz': {'Uzbek': 'Oʻzbekcha'},
  'vi': {'Vietnamese': 'Tiếng Việt'},
  'zh': {'Chinese': '中文'},
  'zu': {'Zulu': 'isiZulu'},
};

///
///
const Map<String, Map<String, String>> LangsTranslationService = {
  'af': {'Afrikaans': 'af'},
  'sq': {'Albanian': 'sq'},
  'am': {'Amharic': 'am'},
  'ar': {'Arabic': 'ar'},
  'hy': {'Armenian': 'hy'},
  'as': {'Assamese': 'as'},
  'ay': {'Aymara': 'ay'},
  'az': {'Azerbaijani': 'az'},
  'bm': {'Bambara': 'bm'},
  'eu': {'Basque': 'eu'},
  'be': {'Belarusian': 'be'},
  'bn': {'Bengali': 'bn'},
  'bho': {'Bhojpuri': 'bho'},
  'bs': {'Bosnian': 'bs'},
  'bg': {'Bulgarian': 'bg'},
  'ca': {'Catalan': 'ca'},
  'ceb': {'Cebuano': 'ceb'},
  'zh-CN': {'Chinese (Simplified)': 'zh-CN'},
  'zh-TW': {'Chinese (Traditional)': 'zh-TW'},
  'co': {'Corsican': 'co'},
  'hr': {'Croatian': 'hr'},
  'cs': {'Czech': 'cs'},
  'da': {'Danish': 'da'},
  'dv': {'Dhivehi': 'dv'},
  'doi': {'Dogri': 'doi'},
  'nl': {'Dutch': 'nl'},
  'en': {'English': 'en'},
  'eo': {'Esperanto': 'eo'},
  'et': {'Estonian': 'et'},
  'ee': {'Ewe': 'ee'},
  'fil': {'Filipino (Tagalog)': 'fil'},
  'fi': {'Finnish': 'fi'},
  'fr': {'French': 'fr'},
  'fy': {'Frisian': 'fy'},
  'gl': {'Galician': 'gl'},
  'ka': {'Georgian': 'ka'},
  'de': {'German': 'de'},
  'el': {'Greek': 'el'},
  'gn': {'Guarani': 'gn'},
  'gu': {'Gujarati': 'gu'},
  'ht': {'Haitian Creole': 'ht'},
  'ha': {'Hausa': 'ha'},
  'haw': {'Hawaiian': 'haw'},
  'he': {'Hebrew': 'he'},
  'hi': {'Hindi': 'hi'},
  'hmn': {'Hmong': 'hmn'},
  'hu': {'Hungarian': 'hu'},
  'is': {'Icelandic': 'is'},
  'ig': {'Igbo': 'ig'},
  'ilo': {'Ilocano': 'ilo'},
  'id': {'Indonesian': 'id'},
  'ga': {'Irish': 'ga'},
  'it': {'Italian': 'it'},
  'ja': {'Japanese': 'ja'},
  'jv': {'Javanese': 'jv'},
  'kn': {'Kannada': 'kn'},
  'kk': {'Kazakh': 'kk'},
  'km': {'Khmer': 'km'},
  'rw': {'Kinyarwanda': 'rw'},
  'gom': {'Konkani': 'gom'},
  'ko': {'Korean': 'ko'},
  'kri': {'Krio': 'kri'},
  'ku': {'Kurdish': 'ku'},
  'ckb': {'Kurdish (Sorani)': 'ckb'},
  'ky': {'Kyrgyz': 'ky'},
  'lo': {'Lao': 'lo'},
  'la': {'Latin': 'la'},
  'lv': {'Latvian': 'lv'},
  'ln': {'Lingala': 'ln'},
  'lt': {'Lithuanian': 'lt'},
  'lg': {'Luganda': 'lg'},
  'lb': {'Luxembourgish': 'lb'},
  'mk': {'Macedonian': 'mk'},
  'mai': {'Maithili': 'mai'},
  'mg': {'Malagasy': 'mg'},
  'ms': {'Malay': 'ms'},
  'ml': {'Malayalam': 'ml'},
  'mt': {'Maltese': 'mt'},
  'mi': {'Maori': 'mi'},
  'mr': {'Marathi': 'mr'},
  'mni-Mtei': {'Meiteilon (Manipuri)': 'mni-Mtei'},
  'lus': {'Mizo': 'lus'},
  'mn': {'Mongolian': 'mn'},
  'my': {'Myanmar (Burmese)': 'my'},
  'ne': {'Nepali': 'ne'},
  'no': {'Norwegian': 'no'},
  'ny': {'Nyanja (Chichewa)': 'ny'},
  'or': {'Odia (Oriya)': 'or'},
  'om': {'Oromo': 'om'},
  'ps': {'Pashto': 'ps'},
  'fa': {'Persian': 'fa'},
  'pl': {'Polish': 'pl'},
  'pt': {'Portuguese (Portugal, Brazil)': 'pt'},
  'pa': {'Punjabi': 'pa'},
  'qu': {'Quechua': 'qu'},
  'ro': {'Romanian': 'ro'},
  'ru': {'Russian': 'ru'},
  'sm': {'Samoan': 'sm'},
  'sa': {'Sanskrit': 'sa'},
  'gd': {'Scots Gaelic': 'gd'},
  'nso': {'Sepedi': 'nso'},
  'sr': {'Serbian': 'sr'},
  'st': {'Sesotho': 'st'},
  'sn': {'Shona': 'sn'},
  'sd': {'Sindhi': 'sd'},
  'si': {'Sinhala (Sinhalese)': 'si'},
  'sk': {'Slovak': 'sk'},
  'sl': {'Slovenian': 'sl'},
  'so': {'Somali': 'so'},
  'es': {'Spanish': 'es'},
  'su': {'Sundanese': 'su'},
  'sw': {'Swahili': 'sw'},
  'sv': {'Swedish': 'sv'},
  'tl': {'Tagalog (Filipino)': 'tl'},
  'tg': {'Tajik': 'tg'},
  'ta': {'Tamil': 'ta'},
  'tt': {'Tatar': 'tt'},
  'te': {'Telugu': 'te'},
  'th': {'Thai': 'th'},
  'ti': {'Tigrinya': 'ti'},
  'ts': {'Tsonga': 'ts'},
  'tr': {'Turkish': 'tr'},
  'tk': {'Turkmen': 'tk'},
  'ak': {'Twi (Akan)': 'ak'},
  'uk': {'Ukrainian': 'uk'},
  'ur': {'Urdu': 'ur'},
  'ug': {'Uyghur': 'ug'},
  'uz': {'Uzbek': 'uz'},
  'vi': {'Vietnamese': 'vi'},
  'cy': {'Welsh': 'cy'},
  'xh': {'Xhosa': 'xh'},
  'yi': {'Yiddish': 'yi'},
  'yo': {'Yoruba': 'yo'},
  'zu': {'Zulu': 'zu'},
};





///
///
// const List<String> supportedLanguagesGoogle = [
//   'af',
//   'sq',
//   'am',
//   'ar',
//   'hy',
//   'az',
//   'eu',
//   'be',
//   'bn',
//   'bs',
//   'bg',
//   'ca',
//   'ceb',
//   'ny',
//   'zh-CN',
//   'zh-TW',
//   'co',
//   'hr',
//   'cs',
//   'da',
//   'nl',
//   'en',
//   'eo',
//   'et',
//   'tl',
//   'fi',
//   'fr',
//   'fy',
//   'gl',
//   'ka',
//   'de',
//   'el',
//   'gu',
//   'ht',
//   'ha',
//   'haw',
//   'iw',
//   'he',
//   'hi',
//   'hmn',
//   'hu',
//   'is',
//   'ig',
//   'id',
//   'ga',
//   'it',
//   'ja',
//   // 'jw',
//   'kn',
//   'kk',
//   'km',
//   'ko',
//   'ku',
//   'ky',
//   'lo',
//   'la',
//   'lv',
//   'lt',
//   'lb',
//   'mk',
//   'mg',
//   'ms',
//   'ml',
//   'mt',
//   'mi',
//   'mr',
//   'mn',
//   'my',
//   'ne',
//   'no',
//   'ps',
//   'fa',
//   'pl',
//   'pt',
//   'pa',
//   'ro',
//   'ru',
//   'sm',
//   'gd',
//   'sr',
//   'st',
//   'sn',
//   'sd',
//   'si',
//   'sk',
//   'sl',
//   'so',
//   'es',
//   'su',
//   'sw',
//   'sv',
//   'tg',
//   'ta',
//   'tt',
//   'te',
//   'th',
//   'tr',
//   'tk',
//   'uk',
//   'ur',
//   'ug',
//   'uz',
//   'vi',
//   'cy',
//   'xh',
//   'yi',
//   'yo',
//   'zu',
// ];

// const List<String> supportedFlutter = [
//   'af',
//   'am',
//   'ar',
//   'as',
//   'az',
//   'be',
//   'bg',
//   'bn',
//   'bs',
//   'ca',
//   'cs',
//   'cy',
//   'da',
//   'de',
//   'el',
//   'en',
//   'es',
//   'et',
//   'eu',
//   'fa',
//   'fi',
//   'fil',
//   'fr',
//   'gl',
//   'gsw',
//   'gu',
//   'he',
//   'hi',
//   'hr',
//   'hu',
//   'hy',
//   'id',
//   'is',
//   'it',
//   'ja',
//   'ka',
//   'kk',
//   'km',
//   'kn',
//   'ko',
//   'ky',
//   'lo',
//   'lt',
//   'lv',
//   'mk',
//   'ml',
//   'mn',
//   'mr',
//   'ms',
//   'my',
//   'nb',
//   'ne',
//   'nl',
//   'no',
//   'or',
//   'pa',
//   'pl',
//   'ps',
//   'pt',
//   'ro',
//   'ru',
//   'si',
//   'sk',
//   'sl',
//   'sq',
//   'sr',
//   'sv',
//   'sw',
//   'ta',
//   'te',
//   'th',
//   'tl',
//   'tr',
//   'uk',
//   'ur',
//   'uz',
//   'vi',
//   'zh',
//   'zu',
// ];

///
///
// const Map<String, Map<String, String>> LANS = {
//   'zh-Hant': {'Chinese (Traditional)': '中文(繁體)'},
//   'hr': {'Croatian': 'Hrvatski'},
//   'cs': {'Czech': 'Čeština'},
//   'da': {'Danish': 'Dansk'},
//   'nl': {'Dutch': 'Nederlands'},
//   'en': {'English': 'English'},
//   'et': {'Estonian': 'Eesti'},
//   'tl': {'Filipino': 'Filipino'},
//   'fi': {'Finnish': 'Suomi'},
//   'fr': {'French': 'Français'},
//   'gl': {'Galician': 'Galego'},
//   'ka': {'Georgian': 'ქართული'},
//   'de': {'German': 'Deutsch'},
//   'el': {'Greek': 'Ελληνικά'},
//   'gu': {'Gujarati': 'ગુજરાતી'},
//   'iw': {'Hebrew': 'עברית'},
//   'hi': {'Hindi': 'हिन्दी'},
//   'hu': {'Hungarian': 'Magyar'},
//   'is': {'Icelandic': 'Íslenska'},
//   'id': {'Indonesian': 'Bahasa Indonesia'},
//   'it': {'Italian': 'Italiano'},
//   'ja': {'Japanese': '日本語'},
//   'jw': {'Javanese': 'Basa Jawa'},
//   'kn': {'Kannada': 'ಕನ್ನಡ'},
//   'kk': {'Kazakh': 'Қазақ тілі'},
//   'km': {'Khmer': 'ភាសាខ្មែរ'},
//   'rw': {'Kinyarwanda': 'Kinyarwanda'},
//   'ko': {'Korean': '한국어'},
//   'ky': {'Kyrgyz': 'Кыргызча'},
//   'lo': {'Lao': 'ພາສາລາວ'},
//   'la': {'Latin': 'Latine'},
//   'lv': {'Latvian': 'Latviešu valoda'},
//   'lt': {'Lithuanian': 'Lietuvių kalba'},
//   'mk': {'Macedonian': 'Македонски'},
//   'mr': {'Marathi': 'मराठी'},
//   'mn': {'Mongolian': 'Монгол'},
//   'my': {'Burmese': 'မြန်မာစာ'},
//   'ne': {'Nepali': 'नेपाली'},
//   'no': {'Norwegian': 'Norsk'},
//   'ps': {'Pashto': 'پښتو'},
//   'fa': {'Persian': 'فارسی'},
//   'pl': {'Polish': 'Polski'},
//   'pt': {'Portuguese': 'Português'},
//   'pa': {'Punjabi': 'ਪੰਜਾਬੀ'},
//   'ro': {'Romanian': 'Română'},
//   'ru': {'Russian': 'Русский'},
//   'sm': {'Samoan': 'Gagana Samoa'},
//   'sr': {'Serbian': 'Српски'},
//   'st': {'Sesotho': 'Sesotho'},
//   'sn': {'Shona': 'ChiShona'},
//   'sd': {'Sindhi': 'سنڌي'},
//   'si': {'Sinhala': 'සිංහල'},
//   'sk': {'Slovak': 'Slovenčina'},
//   'sl': {'Slovenian': 'Slovenščina'},
//   'so': {'Somali': 'Soomaali'},
//   'es': {'Spanish': 'Español'},
//   'sw': {'Swahili': 'Kiswahili'},
//   'sv': {'Swedish': 'Svenska'},
//   'ta': {'Tamil': 'தமிழ்'},
//   'te': {'Telugu': 'తెలుగు'},
//   'th': {'Thai': 'ไทย'},
//   'tr': {'Turkish': 'Türkçe'},
//   'uk': {'Ukrainian': 'Українська'},
//   'ur': {'Urdu': 'اردو'},
//   'uz': {'Uzbek': 'Oʻzbekcha'},
//   'vi': {'Vietnamese': 'Tiếng Việt'},
//   'cy': {'Welsh': 'Cymraeg'},
//   'xh': {'Xhosa': 'isiXhosa'},
//   'yi': {'Yiddish': 'ייִדיש'},
//   'yo': {'Yoruba': 'Yorùbá'},
//   'zu': {'Zulu': 'isiZulu'},
//   'he': {'עברית': 'Hebrew'},
//   'tt': {'Татар': 'Tatar'},
//   'tk': {'Türkmen': 'Turkmen'},
// };
