name: Flutter Package Workflow
description: Build and test a Flutter package.
# эти параметры могут быть использованы в последующих
# шагах workflow для настройки процесса сборки,
# тестирования и анализа кода в зависимости от конфигурации,
# переданной при запуске workflow.

# определения параметров (и их значений по умолчанию),
# которые могут быть переданы в ваш workflow.
# Эти параметры могут затем использоваться в различных
# шагах workflow для настройки поведения действий в
# зависимости от конфигурации.

# required:
# Если значение required установлено в true, то это означает,
#  что параметр является обязательным. При запуске workflow
#   GitHub будет ожидать, что вы предоставите значение для
#   этого параметра. Если значение не предоставлено, GitHub
#   Actions завершит выполнение с ошибкой.
# default:
# Если параметр имеет значение по умолчанию (default), это
# означает, что он не является обязательным. Если при запуске
# workflow значение не передано, то будет использоваться
# значение по умолчанию.

inputs:
  # The Codecov token used to upload coverage
  # codecov_token:
  #   required: true
  #   description: The Codecov token used to upload coverage

  # Whether to collect code coverage
  # collect_coverage:
  #   required: false
  #   default: "true"
  #   description: Whether to collect code coverage

  # Whether to collect the pana score
  # collect_score:
  #   required: false
  #   default: "true"
  #   description: Whether to collect the pana score

  # The value of the concurrency flag (-j) used when running tests
  # concurrency:
  #   required: false
  #   default: "4"
  #   description: The value of the concurrency flag (-j) used when running tests

  # Globs to exclude from coverage
  # coverage_excludes:
  #   required: false
  #   default: ""
  #   description: Globs to exclude from coverage

  # The working directory for this workflow
  # рабочий каталог, в котором будут выполняться все 
  # последующие шаги (steps) workflow.
  working_directory:
    #  значение этого параметра не обязательно.
    required: false
    # указывает, что по умолчанию используется текущий
    # каталог (точка), если значение не предоставлено.
    default: "."
    description: The working directory for this workflow

  # The minimum coverage percentage value
  # min_coverage:
  #   required: false
  #   default: "100"
  #   description: The minimum coverage percentage value

  # Directories to analyze
  analyze_directories:
    required: false
    default: "lib test"
    description: Directories to analyze

  # Directories to report on when collecting coverage
  report_on:
    required: false
    default: "lib"
    description: Directories to report on when collecting coverage

  # Platform to use when running tests
  platform:
    required: false
    default: "vm"
    description: Platform to use when running tests

runs:
  using: "composite"
  steps:
    - name: 🐦 Setup Flutter
      uses: subosito/flutter-action@v2

    - name: 📦 Install Dependencies
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: flutter pub get

    - name: ✨ Format
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: dart format --set-exit-if-changed .

    - name: 🔍 Analyze
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: dart analyze --fatal-warnings ${{inputs.analyze_directories}}

    - name: 🧪 Test
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: |
        if [ -d "test" ]; then
          flutter test --no-pub --test-randomize-ordering-seed random --coverage
        fi

    - name: Exclude Generated Code from Coverage
      if: ${{ inputs.collect_coverage == 'true' && inputs.coverage_excludes != '' }}
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: |
        mv coverage/lcov.info coverage/lcov.info.bak
        sudo apt-get -y install lcov
        lcov --remove coverage/lcov.info.bak "${{inputs.coverage_excludes}}" -o coverage/lcov.info

    - name: 📦 Detect Package Name
      if: inputs.collect_coverage == 'true'
      env:
        PACKAGE_PATH: ${{ inputs.working_directory}}
      id: package
      shell: ${{ inputs.shell }}
      run: echo "name=${PACKAGE_PATH##*/}" >> $GITHUB_OUTPUT

    - name: ⬆️ Upload Coverage
      if: inputs.collect_coverage == 'true'
      uses: codecov/codecov-action@v3
      env:
        PACKAGE_PATH: ${{ inputs.working_directory}}
      with:
        flags: ${{ steps.package.outputs.name }}
        token: ${{ inputs.codecov_token }}

    - name: 📊 Verify Coverage
      if: inputs.collect_coverage == 'true'
      uses: VeryGoodOpenSource/very_good_coverage@v2
      with:
        path: ${{inputs.working_directory}}/coverage/lcov.info
        exclude: ${{inputs.coverage_excludes}}

    - name: 💯 Verify Pub Score
      if: inputs.collect_score == 'true'
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: |
        dart pub global activate pana
        sudo apt-get install webp
        PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
        echo "score: $PANA_SCORE"
        IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
        if [ -z "$1" ]; then MINIMUM_SCORE=TOTAL; else MINIMUM_SCORE=$1; fi
        if (( $SCORE < $MINIMUM_SCORE )); then echo "minimum score $MINIMUM_SCORE was not met!"; exit 1; fi
